### ISSUE TITLE
About:media doesn't report about tabs in other windows

### ISSUE THREAD

**Issue by mirh** [gavinsharp/aboutmedia#3]
@jyavenard
sorry I wouldn't know wherever to ping you otherwise :s

**Comment by jyavenard** [comment]
about:media shows the content of the current window.

if you want to see the media content of the other windows, then simply open another tab on said window and go to about:media.

this can't be changed.

**Comment by jyavenard** [comment]
issue should be closed, however this repository is no longer used and I have no right access.

**Comment by mirh** [comment]
Ok, fine then if it is by design, sorry for the bother. 
I guess you could enable issues tab in your repo? And put a link on the add-on page perhaps?
I dunno. 
Regards.
